// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace MandyLanje_StoreApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Price = 19000m,
                            ProductName = "Monitor"
                        },
                        new
                        {
                            ProductId = 2,
                            Price = 11000m,
                            ProductName = "Adjustable Desk"
                        },
                        new
                        {
                            ProductId = 3,
                            Price = 7999m,
                            ProductName = "Gaming Chair"
                        },
                        new
                        {
                            ProductId = 4,
                            Price = 2400m,
                            ProductName = "Keyboard and Mouse Set"
                        },
                        new
                        {
                            ProductId = 5,
                            Price = 6100m,
                            ProductName = "Case"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
